### ISSUE TITLE
error when server start

### ISSUE THREAD

**Issue by ghost** [Luke100000/ImmersiveArmors#83] opened 2023-03-23 19:59 UTC
```
[21:58:03] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1077]: java.lang.reflect.InvocationTargetException
[21:58:03] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1077]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:58:03] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1077]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[21:58:03] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1077]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:58:03] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1077]:         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[21:58:03] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1077]:         at foxlaunch.FoxServerLauncher.main(FoxServerLauncher.java:33)
[21:58:03] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1077]:         at catserver.server.CatServerLaunch.main(CatServerLaunch.java:8)
[21:58:03] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1077]:         at pro.gravit.launcher.server.ServerWrapper.run(ServerWrapper.java:184)
[21:58:03] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1077]:         at pro.gravit.launcher.server.ServerWrapper.main(ServerWrapper.java:61)
[21:58:03] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1086]: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[21:58:03] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1086]:         at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[21:58:03] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1086]:         at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[21:58:03] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1086]:         at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[21:58:03] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1086]:         at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[21:58:03] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1086]:         at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[21:58:03] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1086]:         at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
[21:58:03] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1086]:         at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
[21:58:03] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1086]:         at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
[21:58:03] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1086]:         ... 8 more
[21:58:03] [main/INFO]: [java.lang.Throwable:printStackTrace:659]: Caused by: java.lang.reflect.InvocationTargetException
[21:58:03] [main/INFO]: [java.lang.Throwable:printStackTrace:659]:      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:58:03] [main/INFO]: [java.lang.Throwable:printStackTrace:659]:      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[21:58:03] [main/INFO]: [java.lang.Throwable:printStackTrace:659]:      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:58:03] [main/INFO]: [java.lang.Throwable:printStackTrace:659]:      at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[21:58:03] [main/INFO]: [java.lang.Throwable:printStackTrace:659]:      at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51)
[21:58:03] [main/INFO]: [java.lang.Throwable:printStackTrace:659]:      at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[21:58:03] [main/INFO]: [java.lang.Throwable:printStackTrace:659]:      ... 15 more
[21:58:03] [main/INFO]: [java.lang.Throwable:printStackTrace:682]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[21:58:03] [main/INFO]: [java.lang.Throwable:printStackTrace:682]:      at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[21:58:03] [main/INFO]: [java.lang.Throwable:printStackTrace:682]:      at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
[21:58:03] [main/INFO]: [java.lang.Throwable:printStackTrace:682]:      at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
[21:58:03] [main/INFO]: [java.lang.Throwable:printStackTrace:682]:      at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
[21:58:03] [main/INFO]: [java.lang.Throwable:printStackTrace:682]:      at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[21:58:03] [main/INFO]: [java.lang.Throwable:printStackTrace:682]:      at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[21:58:03] [main/INFO]: [java.lang.Throwable:printStackTrace:682]:      at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[21:58:03] [main/INFO]: [java.lang.Throwable:printStackTrace:682]:      at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[21:58:03] [main/INFO]: [java.lang.Throwable:printStackTrace:682]:      at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[21:58:03] [main/INFO]: [java.lang.Throwable:printStackTrace:682]:      at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[21:58:03] [main/INFO]: [java.lang.Throwable:printStackTrace:682]:      at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[21:58:03] [main/INFO]: [java.lang.Throwable:printStackTrace:682]:      at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[21:58:03] [main/INFO]: [java.lang.Throwable:printStackTrace:682]:      at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
[21:58:03] [main/INFO]: [java.lang.Throwable:printStackTrace:682]:      at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138)
[21:58:03] [main/INFO]: [java.lang.Throwable:printStackTrace:682]:      at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[21:58:03] [main/INFO]: [java.lang.Throwable:printStackTrace:682]:      at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[21:58:03] [main/INFO]: [java.lang.Throwable:printStackTrace:682]:      at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[21:58:03] [main/INFO]: [java.lang.Throwable:printStackTrace:682]:      at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
[21:58:03] [main/INFO]: [java.lang.Throwable:printStackTrace:682]:      at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138)
[21:58:03] [main/INFO]: [java.lang.Throwable:printStackTrace:682]:      at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[21:58:03] [main/INFO]: [java.lang.Throwable:printStackTrace:682]:      at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[21:58:03] [main/INFO]: [java.lang.Throwable:printStackTrace:682]:      at net.minecraft.server.MinecraftServer.<clinit>(MinecraftServer.java:172)
[21:58:03] [main/INFO]: [java.lang.Throwable:printStackTrace:682]:      at net.minecraft.server.Main.main(Main.java:103)
[21:58:03] [main/INFO]: [java.lang.Throwable:printStackTrace:682]:      ... 21 more
[21:58:03] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:724]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Argument modifier method redirectApplyDamage(F)F in immersive_armors.mixin.json:MixinLivingEntity failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap immersive_armors.mixin.refmap.json
[21:58:03] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:724]:      at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
[21:58:03] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:724]:      at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362)
[21:58:03] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:724]:      at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051)
[21:58:03] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:724]:      at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
[21:58:03] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:724]:      at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
[21:58:03] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:724]:      at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
[21:58:03] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:724]:      at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
[21:58:03] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:724]:      at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[21:58:03] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:724]:      ... 43 more
```

**Comment by Luke100000** [comment] 2023-03-24 06:32
I don't support bukkit implementations (CatServer)

**Comment by Luke100000** [comment] 2023-03-24 06:33
Duplicate of #81

**Closed as completed by Luke100000** 2023-03-24 06:33 UTC
Labels: bug, mod compatibility
